/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import hotelideal.Huesped;
import hotelideal.HuespedData;
import hotelideal.Reserva;
import hotelideal.ReservaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class ListasReservas extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ArrayList<Reserva> obtenerReservas;
private ReservaData reservaData;
private Conexion conexion;
private HabitacionData habitacionData;
private ArrayList<Habitacion> listaHabitaciones;
private HuespedData huespedData;
private ArrayList<Huesped> listaHuespedes;
    /**
     * Creates new form ListasReservas
     */
    public ListasReservas() {
    initComponents();
        try {
        
        conexion = new Conexion("jdbc:mysql://localhost/hotelidealgrupo5", "root", "");
        
        modelo = new DefaultTableModel();
        
        reservaData=new ReservaData (conexion);
        obtenerReservas = (ArrayList) reservaData.obtenerReservas();
        
         habitacionData= new HabitacionData (conexion);
       listaHabitaciones= (ArrayList) habitacionData.obtenerHabitaciones();
       
       huespedData= new HuespedData (conexion);
       listaHuespedes= (ArrayList) huespedData.obtenerHuespedes();
        
        armaCabeceraTabla();
        cargaDatos();
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ListasReservas.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
public void armaCabeceraTabla(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("FECHA INGRESO");
        columnas.add("FECHA SALIDA");
        columnas.add("IMPORTE TOTAL");
        columnas.add("ESTADO");
        columnas.add("HUESPED");
        columnas.add("N°HABITACION");
        columnas.add("CANTIDAD PERSONAS");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        tbReservas.setModel(modelo);
  }
public void cargaDatos(){
            
            
            obtenerReservas =(ArrayList) reservaData.obtenerReservas();
        
        for(Reserva r:obtenerReservas){
     /*       
     boolean l = true;
     String libre = String.valueOf(l);
     libre = estado; 
           
        if (r.getEstado() = true){
            estado="Libre";
        }else {estado="Ocupada";
    }
     */  
        
    
        
    modelo.addRow(new Object[]{r.getId_reserva(),r.getIngreso(),r.getEgreso(),r.getImporte_total(),
        r.getEstado(),r.getHuesped().getNombre(),r.getHabitacion().getNumero(),r.getCantidad_personas()});
            }           
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Hotel ideal");

        tbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReservas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Total de reservas realizadas en el Hotel");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/optucorp_glosario_personal_hoteles02.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReservas;
    // End of variables declaration//GEN-END:variables
}
