/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import hotelideal.Huesped;
import hotelideal.HuespedData;
import hotelideal.Reserva;
import hotelideal.ReservaData;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maqui's
 */
public class ListasCancelarReservas extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ArrayList<Reserva> obtenerReservas;
private ReservaData reservaData;
private Conexion conexion;
private HabitacionData habitacionData;
private ArrayList<Habitacion> listaHabitaciones;
private HuespedData huespedData;
private ArrayList<Huesped> listaHuespedes;
    /**
     * Creates new form ListasReservas
     */
    public ListasCancelarReservas() {
    initComponents();
        try {
        
        conexion = new Conexion("jdbc:mysql://localhost/hotelidealgrupo5", "root", "");
        
        modelo = new DefaultTableModel();
        
        reservaData=new ReservaData (conexion);
        obtenerReservas = (ArrayList) reservaData.obtenerReservas();
        
         habitacionData= new HabitacionData (conexion);
       listaHabitaciones= (ArrayList) habitacionData.obtenerHabitaciones();
       
       huespedData= new HuespedData (conexion);
       listaHuespedes= (ArrayList) huespedData.obtenerHuespedes();
        
       jtIdHuesped.setEditable(false);
       
        armaCabeceraTabla();
        cargaDatos();
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ListasCancelarReservas.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
public void armaCabeceraTabla(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("N° Reserva");
        columnas.add("N° SOCIO");
        columnas.add("FECHA INGRESO");
        columnas.add("FECHA SALIDA");
        columnas.add("IMPORTE TOTAL");
        columnas.add("ESTADO");
        columnas.add("HUESPED");
        columnas.add("N°HABITACION");
        columnas.add("CANTIDAD PERSONAS");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        tbReservas.setModel(modelo);
  }
public void cargaDatos(){
            
            
            obtenerReservas =(ArrayList) reservaData.obtenerReservas();
        
        for(Reserva r:obtenerReservas){
     /*       
     boolean l = true;
     String libre = String.valueOf(l);
     libre = estado; 
           
        if (r.getEstado() = true){
            estado="Libre";
        }else {estado="Ocupada";
    }
     */  
        
    
        
    modelo.addRow(new Object[]{r.getId_reserva(),r.getHuesped().getId_huesped(),r.getIngreso(),r.getEgreso(),r.getImporte_total(),
        r.getEstado(),r.getHuesped().getNombre(),r.getHabitacion().getNumero(),r.getCantidad_personas()});
            }           
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtIdHuesped = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Hotel Ideal");

        tbReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReservas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Total de reservas realizadas en el Hotel");

        jbCancelar.setText("Cancelar Reserva");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese número de reserva");

        jbBuscar.setText("Buscar Huesped por DNI");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("NÚMERO DE SOCIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbBuscar))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jLabel7)
                    .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void borraFilasTabla(){

            int a =modelo.getRowCount()-1;
            System.out.println("Tabla "+a);
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
                
            }
      }
    
    
    
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:

        int id=Integer.parseInt(jtId.getText());
        reservaData.actualizarEstado(false, id);

        JOptionPane.showMessageDialog(null, " La reserva "+id+" se canceló satisfactoriamente ");
        borraFilasTabla();   
        cargaDatos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(JOptionPane.showInputDialog("Ingrese DNI del Huésped"));
        Huesped huesped = huespedData.buscarHuespedPorDni(dni);
        

        if(huesped!=null){
            
            jtIdHuesped.setText(huesped.getId_huesped()+"");
            

        }else{
            JOptionPane.showMessageDialog(this, "El Huésped no se encuentra cargado\n Complete los campos para agregar uno nuevo");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtIdHuesped;
    private javax.swing.JTable tbReservas;
    // End of variables declaration//GEN-END:variables
}
