/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import javax.swing.JFrame;

/**
 *
 * @author Maqui's
 */
public class panelprincipal extends javax.swing.JFrame {

    static void centrarVentana(VistaHuespedes vdh) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form panelprincipal
     */
    public panelprincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        reserva = new javax.swing.JMenu();
        contacto = new javax.swing.JMenuItem();
        habitacion = new javax.swing.JMenu();
        GestiónHabitaciones = new javax.swing.JMenuItem();
        GestionTipo = new javax.swing.JMenuItem();
        GestionHuesped = new javax.swing.JMenu();
        GestionHuespedes = new javax.swing.JMenuItem();
        GestionReserva = new javax.swing.JMenuItem();
        CancelarReserv = new javax.swing.JMenuItem();
        ActuaReserv = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        ListaHab = new javax.swing.JMenuItem();
        ListaHuespe = new javax.swing.JMenuItem();
        ListaReserv = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1026, 555));

        escritorio.setMaximumSize(new java.awt.Dimension(32767, 32767));
        escritorio.setPreferredSize(new java.awt.Dimension(1026, 534));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ImagenFondo.jpg"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 153, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gran Hotel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe Print", 3, 18)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MV Boli", 0, 24))); // NOI18N

        reserva.setBackground(new java.awt.Color(204, 153, 0));
        reserva.setText("Contacto");

        contacto.setText("¿Quienes somos?");
        contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoActionPerformed(evt);
            }
        });
        reserva.add(contacto);

        jMenuBar1.add(reserva);

        habitacion.setText("Gestión hotel");

        GestiónHabitaciones.setText("Gestión habitaciones");
        GestiónHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónHabitacionesActionPerformed(evt);
            }
        });
        habitacion.add(GestiónHabitaciones);

        GestionTipo.setText("Gestión tipo de habitaciones");
        GestionTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionTipoActionPerformed(evt);
            }
        });
        habitacion.add(GestionTipo);

        jMenuBar1.add(habitacion);

        GestionHuesped.setText("Huespedes");
        GestionHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionHuespedActionPerformed(evt);
            }
        });

        GestionHuespedes.setText("Gestión datos huesped");
        GestionHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionHuespedesActionPerformed(evt);
            }
        });
        GestionHuesped.add(GestionHuespedes);

        GestionReserva.setText("Realizar reserva");
        GestionReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionReservaActionPerformed(evt);
            }
        });
        GestionHuesped.add(GestionReserva);

        CancelarReserv.setText("Cancelar Reserva");
        CancelarReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarReservActionPerformed(evt);
            }
        });
        GestionHuesped.add(CancelarReserv);

        ActuaReserv.setText("Actualizar reserva");
        ActuaReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActuaReservActionPerformed(evt);
            }
        });
        GestionHuesped.add(ActuaReserv);

        jMenuBar1.add(GestionHuesped);

        Consultas.setText("Consultas");

        ListaHab.setText("Lista Habitaciones");
        ListaHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaHabActionPerformed(evt);
            }
        });
        Consultas.add(ListaHab);

        ListaHuespe.setText("Lista Huespedes");
        ListaHuespe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaHuespeActionPerformed(evt);
            }
        });
        Consultas.add(ListaHuespe);

        ListaReserv.setText("Lista Reservas");
        ListaReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaReservActionPerformed(evt);
            }
        });
        Consultas.add(ListaReserv);

        jMenuBar1.add(Consultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestiónHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónHabitacionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        Login vh=new Login();
        vh.setVisible(true);
        
        VistaHabitacion l = new VistaHabitacion ();
         l.setVisible(true);
        escritorio.add(l);
        escritorio.moveToFront(l);
        //escritorio.add(vh);
    }//GEN-LAST:event_GestiónHabitacionesActionPerformed

    private void GestionHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionHuespedesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuespedes vh=new VistaHuespedes();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
        //escritorio.add(vh);
    }//GEN-LAST:event_GestionHuespedesActionPerformed

    private void contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        Contacto vh=new Contacto();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
        //escritorio.add(vh);
    }//GEN-LAST:event_contactoActionPerformed

    private void GestionTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionTipoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        Login vh=new Login();
        vh.setVisible(true);
               
        VistaTipoDeHabitacion v=new VistaTipoDeHabitacion();
        v.setVisible(true);
        //vh.setLocation(200, 50);
        
        escritorio.add(v);
        escritorio.moveToFront(v);
        //escritorio.add(vh);
    }//GEN-LAST:event_GestionTipoActionPerformed

    private void GestionHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionHuespedActionPerformed
     /*   // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuespedes vh=new VistaHuespedes();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
        */
    }//GEN-LAST:event_GestionHuespedActionPerformed

    private void ListaHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaHabActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoHabitaciones vh=new ListadoHabitaciones();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_ListaHabActionPerformed

    private void ListaHuespeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaHuespeActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListasHuespedes vh=new ListasHuespedes();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_ListaHuespeActionPerformed

    private void ListaReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaReservActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListasReservas vh=new ListasReservas();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_ListaReservActionPerformed

    private void GestionReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionReservaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaReserva vh=new VistaReserva();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_GestionReservaActionPerformed

    private void CancelarReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarReservActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListasCancelarReservas vh=new ListasCancelarReservas();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_CancelarReservActionPerformed

    private void ActuaReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActuaReservActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ActualizarReserva vh=new ActualizarReserva();
        vh.setVisible(true);
        //vh.setLocation(200, 50);
        escritorio.add(vh);
        escritorio.moveToFront(vh);
    }//GEN-LAST:event_ActuaReservActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActuaReserv;
    private javax.swing.JMenuItem CancelarReserv;
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu GestionHuesped;
    private javax.swing.JMenuItem GestionHuespedes;
    private javax.swing.JMenuItem GestionReserva;
    private javax.swing.JMenuItem GestionTipo;
    private javax.swing.JMenuItem GestiónHabitaciones;
    private javax.swing.JMenuItem ListaHab;
    private javax.swing.JMenuItem ListaHuespe;
    private javax.swing.JMenuItem ListaReserv;
    private javax.swing.JMenuItem contacto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu habitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu reserva;
    // End of variables declaration//GEN-END:variables
}
