/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import hotelideal.Huesped;
import hotelideal.HuespedData;
import hotelideal.Reserva;
import hotelideal.ReservaData;
import hotelideal.TipoDeHabitacion;
import hotelideal.TipoDeHabitacionData;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEBP
 */
public class VistaReserva extends javax.swing.JInternalFrame {
    private HabitacionData habitacionData;
    private TipoDeHabitacionData tipoDeHabitacionData;
    private HuespedData huespedData;
    private ReservaData reservaData;
    private int id_habitacion;
    private DefaultTableModel modelo;
    private ArrayList<Habitacion> listaHabitaciones;
    private ArrayList<TipoDeHabitacion> listaTipoHabitaciones;
    
    private Conexion conexion;
    private int id_huesped;
    
    
  
    /**
     * Creates new form VistaReserva
     */
    public VistaReserva() {
       
        initComponents();
    
       try {
            conexion=new Conexion("jdbc:mysql://localhost/hotelidealgrupo5","root","");
               habitacionData=new HabitacionData(conexion);
               tipoDeHabitacionData=new TipoDeHabitacionData(conexion);
               huespedData = new HuespedData(conexion);
               reservaData = new ReservaData (conexion);
               modelo=new DefaultTableModel();
               listaTipoHabitaciones=(ArrayList) tipoDeHabitacionData.obtenerTipoDeHabitacion();
               listaHabitaciones= (ArrayList) habitacionData.obtenerHabitaciones();
               
               jtCantPersonas.setEditable(false);
               jtPrecio.setEditable(false);
               jtId.setEditable(false);
               jtIdHuesped.setEditable(false);
               jtNombre.setEditable(false);
               jtImporteTotal.setEditable(false);
               
               
               
            armaCabeceraTabla();
            
            
               
               
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btActualizar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtNombre = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        jtIdHuesped = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtCantPersonas = new javax.swing.JTextField();
        jtId = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHabitacion = new javax.swing.JTable();
        cbCantMax = new javax.swing.JComboBox();
        jtIngreso = new javax.swing.JTextField();
        egreso = new javax.swing.JLabel();
        jtEgreso = new javax.swing.JTextField();
        dias = new javax.swing.JLabel();
        jtDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtImporteTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        ingreso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Hotel Ideal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar una Reserva"));
        jPanel1.setToolTipText("");

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Estándar Simple", "Doble", "Triple", "Suite Lujo" }));
        cbTipo.setToolTipText("");
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel7.setText("NÚMERO DE SOCIO");

        jLabel1.setText("Cantidad de Personas");

        jLabel8.setText("N° de Reserva");

        jLabel2.setText("Precio Por Noche");

        tablaHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHabitacion);

        cbCantMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCantMaxActionPerformed(evt);
            }
        });

        jtIngreso.setText("dd/mm/aaaa");

        egreso.setText("CheckOut");

        jtEgreso.setText("dd/mm/aaaa");

        dias.setText("Cantidad de Días");

        jtDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDiasActionPerformed(evt);
            }
        });

        jLabel4.setText("Importe Total");

        jtImporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtImporteTotalActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad de Personas");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar Huesped por DNI");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        ingreso.setText("CheckIn");

        jLabel3.setText("Tipo Habitacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ingreso)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(egreso)
                                        .addGap(25, 25, 25)
                                        .addComponent(jtEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dias)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btActualizar)
                        .addGap(86, 86, 86)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpiar)
                        .addGap(104, 104, 104))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jLabel7)
                    .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(egreso)
                        .addComponent(jtEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ingreso)
                        .addComponent(jtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dias)
                    .addComponent(jtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btActualizar)
                    .addComponent(jbCancelar)
                    .addComponent(jbLimpiar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void armaCabeceraTabla(){
  
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("NUMERO");
        columnas.add("PISO");
        columnas.add("ESTADO");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        tablaHabitacion.setModel(modelo);
  }
      
      public void borraFilasTabla(){

            int a =modelo.getRowCount()-1;
            System.out.println("Tabla "+a);
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
                
            }
      }
      
       public void cargaDatos(){
            
     listaHabitaciones=(ArrayList)habitacionData.obtenerHabitaciones();
    
    
    for(Habitacion item:listaHabitaciones){
        String tipo = (String) cbTipo.getSelectedItem();
        TipoDeHabitacion tipoDeHabitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(tipo);
        String estado;   
        int aux = (int) cbTipo.getSelectedIndex();
        
        
        if(item.isEstado()== true && item.getTipo_de_habitacion().getId_tipo_de_habitacion()==aux){
            modelo.addRow(new Object[]{item.getId_habitacion(), item.getNumero(), item.getPiso(), item.isEstado(), item.getTipo_de_habitacion().getTipo()
                , item.getTipo_de_habitacion().getTipo_camas(), item.getTipo_de_habitacion().getCant_camas(),
                item.getTipo_de_habitacion().getMax_personas(), item.getTipo_de_habitacion().getPrecio_noche()
        });
        }else {estado="Ocupada";
    }
        
    }
       
       }
    
    
    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(JOptionPane.showInputDialog("Ingrese DNI del Huésped"));
        Huesped huesped = huespedData.buscarHuespedPorDni(dni);
        
        if(huesped!=null){
            jtNombre.setText("Bienvenido/a " +huesped.getNombre());
            jtIdHuesped.setText(huesped.getId_huesped()+"");
            
        }else{
            JOptionPane.showMessageDialog(this, "El Huésped no se encuentra cargado\n Complete los campos para agregar uno nuevo");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    public void cargarCantidadPersonas() {
        int max =  Integer.parseInt(jtCantPersonas.getText());
        cbCantMax.removeAllItems();
        for (int i = 0; i <= max; ++i) {
            cbCantMax.addItem(i);
        }
        if(max == 0){
            cbCantMax.addItem("Seleccione");
        }
    }
    
    private void precioypersonas(){
        String tipo = (String) cbTipo.getSelectedItem();
        Reserva reserva = reservaData.buscarReserva(id_huesped);
        TipoDeHabitacion tipoDeHabitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(tipo);
        if(tipoDeHabitacion !=null){
            
            jtCantPersonas.setText(tipoDeHabitacion.getMax_personas()+"");
            
            //double precio = tipoDeHabitacion.getPrecio_noche();
         jtPrecio.setText(tipoDeHabitacion.getPrecio_noche()+"");
                        
            cbTipo.setSelectedItem(tipo);
             
            //cbTipo.setToolTipText(tipoDeHabitacion.getTipo()+"");
            //cbTipoCama.setToolTipText(tipoDeHabitacion.getTipo_camas()+"");
        }else{
          JOptionPane.showMessageDialog(this, "El tipo de habitacion no se encuentra cargada\n Complete los campos para agregar una nueva");
        }
    }
    
    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
        cbTipo.transferFocus();
        borraFilasTabla();
        precioypersonas();
        cargarCantidadPersonas();
        cargaDatos();
        //cargaHabitacion();
    }//GEN-LAST:event_cbTipoActionPerformed

    private void cbCantMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantMaxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCantMaxActionPerformed

  
   
    
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        LocalDate ingreso = LocalDate.parse(jtIngreso.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate egreso = LocalDate.parse(jtEgreso.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
         
        //double importe_total = Integer.parseInt(jtImporteTotal.getText());
        boolean estado = true;
        int cantidad_personas = cbCantMax.getSelectedIndex();
        if (tablaHabitacion.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, tablaHabitacion.getSelectedRow() + " Debe seleccionar una habitación ");
        }
        //TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(cbTipo.getSelectedItem()+"");
        //String tipo_de_habitacion = (String) cbTipo.getSelectedItem();
        
        
        Habitacion habitacion = habitacionData.buscarHabitacion(id_habitacion);
        Huesped huesped = huespedData.buscarHuesped(Integer.parseInt(jtIdHuesped.getText()));
        habitacion = habitacionData.buscarHabitacion((int) tablaHabitacion.getValueAt(tablaHabitacion.getSelectedRow(), 0));
        
        int dias = Integer.parseInt(jtDias.getText());
        double precio = habitacion.getTipo_de_habitacion().getPrecio_noche();
        
       // int precio = Integer.parseInt(jtPrecio.getText());
        
        double importe_total = dias * precio;
               
        
         jtImporteTotal.setText(importe_total+"");
       // double precio_noche = habitacion.getTipo_de_habitacion().getPrecio_noche();
                
              
        Reserva reserva=new Reserva(ingreso, egreso, cantidad_personas, importe_total, estado, huesped, habitacion);
        reserva.setHabitacion(habitacion);
        
        
        reservaData.crearReserva(reserva);         
        jtId.setText(reserva.getId_reserva()+"");
        
        int id_habitacion = habitacion.getId_habitacion();
        habitacionData.cambiarEstado(false, id_habitacion);
        
        String id = (String) jtId.getText();
        JOptionPane.showMessageDialog(this, "Su numero de reserva es: " + id); 
    }//GEN-LAST:event_btGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        
        int id=Integer.parseInt(jtId.getText());
        reservaData.actualizarEstado(false, id);
        
        JOptionPane.showMessageDialog(null, " La reserva "+id+" se canceló satisfactoriamente ");
         
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        LocalDate ingreso = LocalDate.parse(jtIngreso.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate egreso = LocalDate.parse(jtEgreso.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        double importe_total = Integer.parseInt(jtImporteTotal.getText());
        boolean estado = true;
        int cantidad_personas = cbCantMax.getSelectedIndex();
        if (tablaHabitacion.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, tablaHabitacion.getSelectedRow() + " Debe seleccionar una habitación ");
        }
        //TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(cbTipo.getSelectedItem()+"");
        //String tipo_de_habitacion = (String) cbTipo.getSelectedItem();
        
        
        Habitacion habitacion = habitacionData.buscarHabitacion(id_habitacion);
        Huesped huesped = huespedData.buscarHuesped(Integer.parseInt(jtIdHuesped.getText()));
        habitacion = habitacionData.buscarHabitacion((int) tablaHabitacion.getValueAt(tablaHabitacion.getSelectedRow(), 0));
        
        
        Reserva reserva=new Reserva(ingreso, egreso, cantidad_personas, importe_total, estado, huesped, habitacion);
        reserva.setHabitacion(habitacion);
        
        
        reservaData.actualizarReserva(reserva);         
        jtId.setText(reserva.getId_reserva()+"");
        
        int id_habitacion = habitacion.getId_habitacion();
        habitacionData.cambiarEstado(false, id_habitacion);
        
        String id = (String) jtId.getText();
        JOptionPane.showMessageDialog(this, "Su numero de reserva es: " + id); 
    }//GEN-LAST:event_btActualizarActionPerformed

     
    
    private void jtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDiasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtDiasActionPerformed

    private void jtImporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtImporteTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtImporteTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JComboBox cbCantMax;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel dias;
    private javax.swing.JLabel egreso;
    private javax.swing.JLabel ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JTextField jtCantPersonas;
    private javax.swing.JTextField jtDias;
    private javax.swing.JTextField jtEgreso;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtIdHuesped;
    private javax.swing.JTextField jtImporteTotal;
    private javax.swing.JTextField jtIngreso;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTable tablaHabitacion;
    // End of variables declaration//GEN-END:variables
}
