/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Huesped;
import hotelideal.HuespedData;
import hotelideal.Reserva;
import hotelideal.ReservaData;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandra
 */
public class VistaHuespedes extends javax.swing.JInternalFrame {
    private int id_huesped, dni;    
    private String nombre, domicilio, correo;
    private long celular;
    private HuespedData huespedData;
    private Conexion conexion;
    private ReservaData reservaData;
    private DefaultTableModel modelo;
    private ArrayList<Reserva> listaDeReservas;
    private ArrayList<Huesped> listaHuespedes;
    
    /**
     * Creates new form VistaHuespedes
     */
    public VistaHuespedes() {
        initComponents();
        
        try {
        conexion = new Conexion("jdbc:mysql://localhost/hotelidealgrupo5", "root", "");
        huespedData = new HuespedData(conexion);
        //reservaData = new ReservaData(conexion);
        
        modelo=new DefaultTableModel();
        
        //listaDeReservas = (ArrayList)reservaData.obtenerReservas();
        listaHuespedes= (ArrayList)huespedData.obtenerHuespedes();
        
        jtIdHuesped.setEditable(false);
        
        //armaCabeceraTablaInforme();
        
        
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(VistaHuespedes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTabla = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BuscarXDNI = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jBActualizar = new javax.swing.JButton();
        jtIdHuesped = new javax.swing.JTextField();
        jLDni = new javax.swing.JLabel();
        jBBorrarH = new javax.swing.JButton();
        jLDomicilio = new javax.swing.JLabel();
        jBAgregarH = new javax.swing.JButton();
        jLCorreo = new javax.swing.JLabel();
        jLCelular = new javax.swing.JLabel();
        jTNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        btLimpiar = new javax.swing.JButton();
        jTDom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTCorr = new javax.swing.JTextField();
        jTCel = new javax.swing.JTextField();

        jLabel5.setText("Complete los campos  para agregar un nuevo huesped.");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Hotel Ideal");
        setPreferredSize(new java.awt.Dimension(400, 636));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión Huesped"));

        jLabel6.setText("Si es un cliente ya registrado");

        BuscarXDNI.setText("BUSCAR POR DNI");
        BuscarXDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarXDNIActionPerformed(evt);
            }
        });

        jLabel7.setText("N° Socio");

        jLNombre.setText("Nombre");

        jBActualizar.setText("Actualizar Datos");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jLDni.setText("DNI");

        jBBorrarH.setText("Borrar");
        jBBorrarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarHActionPerformed(evt);
            }
        });

        jLDomicilio.setText("Domicilio");

        jBAgregarH.setText("Guardar");
        jBAgregarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarHActionPerformed(evt);
            }
        });

        jLCorreo.setText("Correo");

        jLCelular.setText("Celular");

        jTNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ImagenHuespedes_1.jpg"))); // NOI18N

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Complete los campos  para agregar un nuevo huesped.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLDomicilio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTNom)
                                            .addComponent(jTDni)
                                            .addComponent(jTDom)
                                            .addComponent(jTCorr)
                                            .addComponent(jTCel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAgregarH, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBorrarH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(BuscarXDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BuscarXDNI, jBActualizar, jBAgregarH, jBBorrarH});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtIdHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarH)
                    .addComponent(jBActualizar)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btLimpiar)
                        .addComponent(jBBorrarH))
                    .addComponent(BuscarXDNI))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(nombreTabla)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addGap(168, 168, 168)
                .addComponent(nombreTabla)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 743, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void jBBorrarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarHActionPerformed
        // TODO add your handling code here:
        
        int dni = Integer.parseInt(JOptionPane.showInputDialog("Ingrese DNI del Huésped"));
        /*
        int id_reserva = -1;
             
        for(Reserva r:listaDeReservas){
            if (r.getHuesped().getDni()==dni){
                id_reserva=r.getId_reserva();
            //nuevalista.add(r);
            }
        }
        
        if (id_reserva>-1){
            JOptionPane.showMessageDialog(null, "No se puede borrar porque tiene una reserva cargada en la base de datos");
  
        }else{*/
            huespedData.borrarHuespedPorDni(dni);
            JOptionPane.showMessageDialog(null, "Eliminación exitosa");
            jTNom.setText(""); jTDni.setText(""); jTDom.setText("");
            jTCorr.setText(""); jTCel.setText(""); jtIdHuesped.setText("");
            
        
        
        
    }//GEN-LAST:event_jBBorrarHActionPerformed

    private void jBAgregarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarHActionPerformed
        // TODO add your handling code here:
        
        
        int check= 0;
        nombre = jTNom.getText();
        dni=Integer.parseInt(jTDni.getText());
        domicilio =jTDom.getText();
        correo=jTCorr.getText();
        celular= Integer.parseInt(jTCel.getText());
      //id_huesped= Integer.parseInt(jtIdHuesped.getText());
       
        for(Huesped h:listaHuespedes){
               if(h.getDni()==dni){
                   check+=1;
                }
            }
        if(check>0){
            JOptionPane.showMessageDialog(this, "Ya hay cargado un Huesped con ese DNI");     
        }else{
             Huesped huesped = new Huesped(nombre ,dni ,domicilio ,correo ,celular );
       huespedData.guardarHuesped(huesped);
       
        jtIdHuesped.setText(huesped.getId_huesped()+"");
                
                       JOptionPane.showMessageDialog(this, "¡¡Huésped ingresado!!");
        }
                          

         
    }//GEN-LAST:event_jBAgregarHActionPerformed

    private void jTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        
        nombre = jTNom.getText();
        dni = Integer.parseInt(jTDni.getText());
        domicilio = jTDom.getText();
        correo = jTCorr.getText();
        celular = Integer.parseInt(jTCel.getText());
        id_huesped = Integer.parseInt(jtIdHuesped.getText());
       // id_huesped = huespedData.buscarHuespedPorDni(dni).getId_huesped();
        
        Huesped huesped =new Huesped(id_huesped ,nombre ,dni ,domicilio ,correo ,celular);
        
        huespedData.actualizarHuesped(huesped);
        JOptionPane.showMessageDialog(this, "¡¡Datos de Huésped actualizado!!");
        
        
        
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void BuscarXDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarXDNIActionPerformed
        // TODO add your handling code here:
        
        int porDni = Integer.parseInt(JOptionPane.showInputDialog("Ingrese DNI del Huésped"));
        Huesped huesped = huespedData.buscarHuespedPorDni(porDni);
        
        if(huesped!=null){
            jTNom.setText(huesped.getNombre());
            jTDni.setText(huesped.getDni()+"");
            jTDom.setText(huesped.getDomicilio());
            jTCorr.setText(huesped.getCorreo());
            jTCel.setText(huesped.getCelular()+"");
            jtIdHuesped.setText(huesped.getId_huesped()+"");
            //id_huesped = huesped.getId_huesped();
        }else{
            JOptionPane.showMessageDialog(this, "El Huésped no se encuentra cargado\n Complete los campos para agregar uno nuevo");
        }
    }//GEN-LAST:event_BuscarXDNIActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed

        jTNom.setText(""); jTDni.setText(""); jTDom.setText("");
        jTCorr.setText(""); jTCel.setText("");
        nombreTabla.setText(""); jtIdHuesped.setText("");
       // borraFilasTabla();
        //modelo.setColumnCount(0);
        //armaCabeceraTablaInforme();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btLimpiarActionPerformed
/*
 public void borraFilasTabla(){

            int a =modelo.getRowCount()-1;
            System.out.println("Tabla "+a);
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
                System.out.println("Tabla "+i);
            }
      }
 
 public void armaCabeceraTablaInforme(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("Id Reserva");
        columnas.add("Estado Reserva");
        columnas.add("Fecha Ingreso");
        columnas.add("Fecha Egreso");
        columnas.add("Nro Habitacion");
        columnas.add("Tipo Habitacion");
        columnas.add("Monto");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
        //tablaHuesped.setModel(modelo);
  }
 
 public void armaCabeceraTablaListar(){
    
        //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("Nombre");
        columnas.add("DNI");
        columnas.add("Domicilio");
        columnas.add("Correo");
        columnas.add("Celular");
        columnas.add("Habitacion");
        columnas.add("Piso");
        for(Object it:columnas){
        
            modelo.addColumn(it);
        }
//        tablaHuesped.setModel(modelo);
  }
 */
 public String estado(boolean buleano){
     
     if(buleano){
         return "ACTIVA";
     }else{
         return "INACTIVA";
     }
     
 }
 

    
       
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarXDNI;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBAgregarH;
    private javax.swing.JButton jBBorrarH;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCel;
    private javax.swing.JTextField jTCorr;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTDom;
    private javax.swing.JTextField jTNom;
    private javax.swing.JTextField jtIdHuesped;
    private javax.swing.JLabel nombreTabla;
    // End of variables declaration//GEN-END:variables
}
