/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelideal.vistas;

import hotelideal.Conexion;
import hotelideal.Habitacion;
import hotelideal.HabitacionData;
import hotelideal.TipoDeHabitacion;
import hotelideal.TipoDeHabitacionData;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VistaHabitacion extends javax.swing.JInternalFrame {
  private HabitacionData habitacionData;
  private TipoDeHabitacionData tipoDeHabitacionData;
  private int id_habitacion;
  private Conexion conexion;
  
    
    public VistaHabitacion() {
        initComponents();
    
       try {
            conexion=new Conexion("jdbc:mysql://localhost/hotelidealgrupo5","root","");
               habitacionData=new HabitacionData(conexion);
               tipoDeHabitacionData=new TipoDeHabitacionData(conexion);
               
               //JtId.setEnabled(false);
               
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevahabitacion = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        piso = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        JtNumero = new javax.swing.JTextField();
        JtPiso = new javax.swing.JTextField();
        BtGuardar = new javax.swing.JButton();
        BtLimpiar = new javax.swing.JButton();
        BtModificar = new javax.swing.JButton();
        BtBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JtId = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        JtTipo = new javax.swing.JTextField();
        jcOcupado = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        nuevahabitacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nuevahabitacion.setText("HABITACIÓN");

        numero.setText("Numero");

        piso.setText("Piso");

        estado.setText("Estado");

        tipo.setText("Tipo de habitacion");

        JtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNumeroActionPerformed(evt);
            }
        });

        JtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtPisoActionPerformed(evt);
            }
        });

        BtGuardar.setText("Guardar");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });

        BtLimpiar.setText("Limpiar");
        BtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimpiarActionPerformed(evt);
            }
        });

        BtModificar.setText("Actualizar");
        BtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtModificarActionPerformed(evt);
            }
        });

        BtBorrar.setText("Borrar");
        BtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        jcOcupado.setText("Libre");
        jcOcupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcOcupadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevahabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BtModificar)
                        .addGap(18, 18, 18)
                        .addComponent(BtBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(BtLimpiar))
                    .addComponent(piso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JtTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(JtId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtPiso, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(BtBuscar))
                            .addComponent(jcOcupado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nuevahabitacion)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numero)
                    .addComponent(JtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(piso)
                    .addComponent(JtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado)
                    .addComponent(jcOcupado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(JtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardar)
                    .addComponent(BtModificar)
                    .addComponent(BtBorrar)
                    .addComponent(BtLimpiar))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

       
    private void JtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtPisoActionPerformed

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(JtNumero.getText());
        int piso = Integer.parseInt(JtPiso.getText());
        boolean estado = jcOcupado.isSelected();
            if (jcOcupado.isSelected()){
                estado = true;
            } else{estado=false;}
        TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(JtTipo.getText());     
        Habitacion habitacion=new Habitacion(numero,piso,estado,tipo_de_habitacion);
        habitacionData.guardarHabitacion(habitacion);         
        JtId.setText(habitacion.getId_habitacion()+"");
        JOptionPane.showMessageDialog(rootPane, "La Habitacion Nro "+ numero +" se guardó Correctamente");   
    }//GEN-LAST:event_BtGuardarActionPerformed

    private void BtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimpiarActionPerformed
        // TODO add your handling code here:
        JtId.setText("");
        JtNumero.setText("");
        JtPiso.setText("");
       jcOcupado.setSelected(false);
        
        JtTipo.setText("");
    }//GEN-LAST:event_BtLimpiarActionPerformed

    private void JtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNumeroActionPerformed

    private void BtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(JtId.getText());
        habitacionData.borrarHabitacion(id);
        
         JOptionPane.showMessageDialog(null, " La habitación se borró satisfactoriamente ");
    }//GEN-LAST:event_BtBorrarActionPerformed

    private void BtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtModificarActionPerformed
        // TODO add your handling code here:
        if(JtId.getText()!=null){    
        int id_habitacion = Integer.parseInt(JtId.getText());
        int numero = Integer.parseInt(JtNumero.getText());
        int piso = Integer.parseInt(JtPiso.getText());
        boolean estado = jcOcupado.isSelected();
            if (jcOcupado.isSelected()){
                estado = true;
            } else{estado=false;}
        TipoDeHabitacion tipo_de_habitacion = tipoDeHabitacionData.buscarxTipoDeHabitacion(JtTipo.getText());     
        Habitacion habitacion=new Habitacion(id_habitacion,numero,piso,estado,tipo_de_habitacion);
        habitacionData.actualizarHabitacion(habitacion);         
        //JtId.setText(habitacion.getId_habitacion()+"");
        JOptionPane.showMessageDialog(rootPane, "La Habitacion Nro "+ numero +" se modificó Correctamente");  
        }
       
        /*
        TipoDeHabitacion tipo_de_habitacion = new TipoDeHabitacion();
        tipo_de_habitacion.getTipo();
        tipoDeHabitacionData.buscarxTipoDeHabitacion(tipo_de_habitacion.getTipo());
        
        tipoDeHabitacionData.buscarxTipoDeHabitacion(JtTipo.getText());
        TipoDeHabitacion tipo_de_habitacion = JtTipo.getText();
        */
        
         
    }//GEN-LAST:event_BtModificarActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(JtId.getText());
        Habitacion habitacion = habitacionData.buscarHabitacion(id);
        if (habitacion!=null) {
            JtId.setText(habitacion.getId_habitacion()+"");
            JtNumero.setText(habitacion.getNumero()+"");
            JtPiso.setText(habitacion.getPiso()+"");
            //jcOcupado.setText(habitacion.getEstado()+"");
            if(habitacion.isEstado()){
                    jcOcupado.setSelected(true);
                    
                }
                
            //jcOcupado.setVisible(habitacion.getEstado());
            JtTipo.setText(habitacion.getTipo_de_habitacion().getTipo());
            }else{
          JOptionPane.showMessageDialog(this, "La habitacion no se encuentra cargada\n Complete los campos para agregar una nueva");
        }
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void jcOcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcOcupadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcOcupadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBorrar;
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JButton BtLimpiar;
    private javax.swing.JButton BtModificar;
    private javax.swing.JTextField JtId;
    private javax.swing.JTextField JtNumero;
    private javax.swing.JTextField JtPiso;
    private javax.swing.JTextField JtTipo;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jcOcupado;
    private javax.swing.JLabel nuevahabitacion;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel piso;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
